# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ubuntu MATE
email: code@ubuntu-mate.org

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ubuntu-mate.org" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

# Plugins
plugins:
    - jekyll-feed
    - jekyll-last-modified-at
    - jemoji

feed:
    path: rss.xml

# Workaround: i18n plugin causes CSS generation to output a source map.
# https://github.com/untra/polyglot/issues/107
sass:
    sourcemap: never

# Exclude from processing.
exclude:
    - Gemfile
    - Gemfile.lock
    - EDITING.md
    - README.md
    - LICENSE.md
    - scripts
    - i18n
    - vendor
    - .git
    - .github
    - .tx

# Network URLs
launchpad: "https://launchpad.net/ubuntu-mate"
github: "https://github.com/ubuntu-mate/"
irc: "/irc/"
facebook: "https://www.facebook.com/UbuntuMATEedition/"
twitter: "https://twitter.com/ubuntu_mate"
rss: "/rss.xml"
rss_discourse: "https://ubuntu-mate.community/latest.rss"
discourse: "https://ubuntu-mate.community"
translate: "https://www.transifex.com/ubuntu-mate/ubuntu-mate-org"
discord: "https://discord.gg/T8NDH5RaEj"

# i18n
languages: ["en", "fr", "ru"]
default_lang: "en"
exclude_from_localization: [
    "assets",
    "images"
]
parallel_localization: true
