name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Cache RubyGems
      uses: actions/cache@v2
      env:
        cache-name: rubygems
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ruby ruby-dev ruby-bundler make gcc
        sudo apt-get install transmission-cli python3-requests python3-yaml translate-toolkit rsync python3-polib webp
        bundle config path vendor/bundle
        bundle install --jobs=4

    - name: Build Website
      run: |
        scripts/build.sh --magnet-uri

    - name: Proofing
      run: |
        scripts/test.sh

    - name: Build Website with locales
      run: |
        scripts/build.sh --locales

    - name: Proofing with locales
      run: |
        scripts/test.sh

    - name: Generate WebP images
      run: |
        scripts/helpers/generate-webp.sh

    - name: Deploy to server
      if: ${{ github.event_name == 'push' && github.repository == 'ubuntu-mate/ubuntu-mate.org' }}
      run: |
        mkdir -p $HOME/.ssh/
        chmod 700 $HOME/.ssh/
        echo -n "${{ secrets.SSH_MATEY }}" > $HOME/.ssh/id_rsa
        chmod 600 $HOME/.ssh/id_rsa
        scripts/deploy.sh
